services:
  - type: web
    name: bitton-backend
    runtime: node
    region: ohio
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx prisma db push --skip-generate && npm run build
    startCommand: npm run start
    nodeVersion: 20.20.0
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # set manually in Render dashboard
      - key: RPC_URL
        value: https://sepolia.base.org
      - key: CHAIN_ID
        value: "84532"
      - key: RELAYER_PRIVATE_KEY
        sync: false
      - key: BTN_TOKEN_ADDRESS
        value: "0x5b964baafEDf002e5364F37848DCa1908D3e4e9f"
      - key: USDT_TOKEN_ADDRESS
        value: "0x69Bc9E30366888385f68cBB566EEb655CD5A34CC"
      - key: USDC_TOKEN_ADDRESS
        value: "0x69Bc9E30366888385f68cBB566EEb655CD5A34CC"
      - key: CUSTODIAL_ADDRESS
        value: "0x71dB030B792E9D4CfdCC7e452e0Ff55CdB5A4D99"
      - key: VAULT_MANAGER_ADDRESS
        value: "0xC5Ab43f26C1BacA8137cf4E4e1Ba98933D30C553"
      - key: STAKING_VAULT_ADDRESS
        value: "0xf246C58FB64dAf6DA751Ea7d2c8db7d38E7a6C4B"
      - key: REWARD_ENGINE_ADDRESS
        value: "0x97d1d86c709F4d5aEb93f46A60A16941c03076c0"
      - key: VESTING_POOL_ADDRESS
        value: "0x79D2CA5fb7ACF936198ec823a006a34cB611389e"
      - key: WITHDRAWAL_WALLET_ADDRESS
        value: "0xa523b6B9c3F2191C02ACfEc92C319D66315a3768"
      - key: BONUS_ENGINE_ADDRESS
        value: "0x20189fFfa3B42B7D32b88376681D9c0Fec4A1eDC"
      - key: RESERVE_FUND_ADDRESS
        value: "0x8B7917daff5695461CFFDdCF5AA3dC7cC310793D"
      - key: AUTH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRY
        value: "15m"
      - key: JWT_REFRESH_EXPIRY
        value: "7d"
      - key: ADMIN_API_KEY
        sync: false
      - key: EMAIL_API_KEY
        sync: false
      - key: EMAIL_API_PROVIDER
        value: resend
      - key: SMTP_FROM
        value: "noreply@bitton.ai"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        value: bitton_auth_bot
      - key: APP_URL
        value: "https://bitton-contracts.vercel.app"
